parameters:
  
services:

  cerad_auth__oauth__provider_manager:
    class: Cerad\Bundle\AuthBundle\OAuth\ProviderManager
    arguments:  
      - '@security.http_utils'
      - '%cerad_auth__oauth__redirect%'
      - '%cerad_auth__oauth__providers%'
      - '%kernel.secret%'
      
  cerad_auth__oauth__controller:
    class: Cerad\Bundle\AuthBundle\OAuth\OAuthController
    arguments:  
      - '@cerad_auth__oauth__provider_manager'
      - '%kernel.secret%'
      
  cerad_auth__auth__controller:
    class: Cerad\Bundle\AuthBundle\Auth\AuthController
    arguments:  
    - '%kernel.secret%'
    - '%cerad_auth__auth__users%'

  cerad_auth__auth__user_provider:
    class: Cerad\Bundle\AuthBundle\Auth\AuthUserProvider
    arguments:  
      - '%cerad_auth__auth__users%'
      
  cerad_auth__auth__authenticator:
    class: Cerad\Bundle\AuthBundle\Auth\AuthAuthenticator
    arguments:
      - '%kernel.secret%'
  

