cerad_auth:
  oauth:
    redirect: cerad_auth__oauth__redirect
    providers:
      -
        name:  google
        class: Cerad\Bundle\AuthBundle\OAuth\Provider\GoogleProvider
        client_id:     %google_client_id%
        client_secret: %google_client_secret%
      -
        name: facebook
        class: Cerad\Bundle\AuthBundle\OAuth\Provider\FacebookProvider
        client_id:     %facebook_client_id%
        client_secret: %facebook_client_secret%
      -
        name: github
        class: Cerad\Bundle\AuthBundle\OAuth\Provider\GithubProvider
        client_id:     %github_client_id%
        client_secret: %github_client_secret%
      -
        name: linkedin
        class: Cerad\Bundle\AuthBundle\OAuth\Provider\LinkedinProvider
        client_id:     %linkedin_client_id%
        client_secret: %linkedin_client_secret%
      -
        name: twitter
        class: Cerad\Bundle\AuthBundle\OAuth\Provider\TwitterProvider
        client_id:     %twitter_client_id%
        client_secret: %twitter_client_secret%
        
  users:
    ahundiak:
      provider:   google
      identifier: 110360268001715642098
      name:       Art Hundiak
      roles:      ['ROLE_SRA' ]
    nasoa:    { identifier: pass1, roles: [ 'ROLE_USER' ] }
    sra:      { identifier: pass2, roles: [ 'ROLE_SRA'  ] }
    assignor: { identifier: pass2, roles: [ 'ROLE_ASSIGNOR' ] }
