security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext

  role_hierarchy:
    ROLE_SRA:         [ROLE_USER, ROLE_ASSIGNOR]
    ROLE_ASSIGNOR:    [ROLE_USER]
        
    ROLE_ADMIN:       [ROLE_USER, ROLE_ASSIGNOR, ROLE_SRA]
    ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    cerad_auth__auth__user_provider:
      id: cerad_auth__auth__user_provider
    in_memory:
      memory:
        users: # Not used
          nasoa:    { password: pass1, roles: [ 'ROLE_USER' ] }
          sra:      { password: pass2, roles: [ 'ROLE_SRA'  ] }
          assignor: { password: pass2, roles: [ 'ROLE_ASSIGNOR' ] }

  firewalls:
    dev:
      pattern:  ^/(_(profiler|wdt)|css|images|js)/
      security: false
            
    main:
      pattern: ^/
      stateless: true
      anonymous: true
      simple_preauth:
        provider:      cerad_auth__auth__user_provider
        authenticator: cerad_auth__auth__authenticator
        
  access_control:
    - { path: ^/referees, roles: ROLE_ASSIGNOR }